### ISSUE TITLE
Only javascript language works

### ISSUE THREAD

**Issue by perilouspete** [serdarciplak/BlazorMonaco#104]
Hi 

I have changed the language to csharp but then there is no completion the only language that works is javascript

private StandaloneEditorConstructionOptions EditorConstructionOptions(StandaloneCodeEditor editor)
{
    return new StandaloneEditorConstructionOptions
    {
        Language = "csharp"
        
    };
}

Am I doing something wrong?

**Comment by bao86** [comment]
Up :)
How can we change language ?

**Comment by serdarciplak** [comment]
The language support is managed by Monaco Editor and as it supports "csharp" as a language, BlazorMonaco also supports that. Is it possible that you may have a custom integration? For example, the library mentioned [here](https://github.com/serdarciplak/BlazorMonaco/issues/59) is said to be supporting only JSON and YAML. This may be a similar thing.

**Comment by serdarciplak** [comment]
As you can see [here](https://microsoft.github.io/monaco-editor/), Monaco Editor (and thus BlazorMonaco) supports `csharp`. You can use the `StandaloneEditorConstructionOptions.Language` property in BlazorMonaco to set the language of an editor instance.
