### ISSUE TITLE
GetValue not returning when the value is large.

### ISSUE THREAD

**Issue by Hirad2hhk** [serdarciplak/BlazorMonaco#106]
I encountered this problem when i copied a websites source html and i found out that when the editor component is used in blazor server side and the file is larger than 30Kbs(roughly 1000 lines) the method wont return and crashes.
This is easily reproduceable by running the sample app in the repository as blazor server-side and pressing the get value button when a large enough text is in the editor.

**Comment by Hirad2hhk** [comment]
This is the link to a test repository I created for anyone intrested

**Comment by Hirad2hhk** [comment]
This is a link to the test repository i created for anyone intrested 
https://github.com/Hirad2hhk/FaultyMonaco

**Comment by MikeWilliams-UK** [comment]
Just tried this solution and I see same the exact same symptoms when the string pasted into the editor is 260k bytes as I have desribed in #109

**Comment by MikeWilliams-UK** [comment]
Similar belaviour is seen in Manaco Playground - Issue raised there.
https://github.com/microsoft/monaco-editor/issues/4238

**Comment by da-baranov** [comment]
services.AddSignalR(e => {
            e.MaximumReceiveMessageSize = 1024 * 1024 * 100;
        });

**Comment by MikeWilliams-UK** [comment]
@Hirad2hhk you might want to try the above, it worked for my app

**Comment by Hirad2hhk** [comment]
Thank you very much @MikeWilliams-UK and @da-baranov  . The issue got fixed
