### ISSUE TITLE
AutomaticLayout? Does it work? 

### ISSUE THREAD

**Issue by Puliczek** [serdarciplak/BlazorMonaco#11]
`AutomaticLayout = true`

Should It work on width and height?
I am trying to get it work with https://split.js.org/
However, it doesn't work :( 

![image](https://user-images.githubusercontent.com/12344862/87073968-7d95d400-c21e-11ea-8f8c-a5625c8a5995.png)
![image](https://user-images.githubusercontent.com/12344862/87074062-a1591a00-c21e-11ea-8141-a395dfa40c47.png)

On start is working, otherwise when I drag gutter horizontal to resize width is cutting editor. ;/

![image](https://user-images.githubusercontent.com/12344862/87074414-1c223500-c21f-11ea-9c60-01b94ca46155.png)

**Comment by serdarciplak** [comment]
Hi @Puliczek 

BlazorMonaco is just a bridge between Blazor and Monaco Editor's JavaScript API. So, all these settings are actually Monaco Editor's settings about which you can get more detail via their documentation (https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.istandaloneeditorconstructionoptions.html#automaticlayout) BlazorMonaco does not alter the way things work.

By the way; Monaco Editor documentation says when you enable automatic layout, it checks whether the parent size has changed on an interval and it's not suggested for performance. If you can get an event on size changes, you can call editor's layout method manually.
