### ISSUE TITLE
Please consider updating the embedded version of the Monaco Editor

### ISSUE THREAD

**Issue by MikeWilliams-UK** [serdarciplak/BlazorMonaco#112]
Firstly, Thank you for the excellent NuGet package.

The current version of the Monaco Editor used by your NuGet package seems to be 0.34.1
https://microsoft.github.io/monaco-editor/playground.html shows that the latest version is 0.44.0

On https://github.com/microsoft/monaco-editor the history for the file CHANGELOG.md shows that 0.34.1 was produced around Oct 17, 2022

![image](https://github.com/serdarciplak/BlazorMonaco/assets/13162784/bba56001-24bc-440e-b3ec-c6dfb6d4d9c3)

**Comment by serdarciplak** [comment]
Looks like 0.46.0 is released since your message. I'll update to the latest version and release a new version. Thanks!
