### ISSUE TITLE
Dotnet 8 Support

### ISSUE THREAD

**Issue by DanielCordell** [serdarciplak/BlazorMonaco#114]
Dotnet 8 was release a few weeks ago https://dotnet.microsoft.com/en-us/download/dotnet/8.0

Would be great to get support for this. I'm happy to take a crack at this.

**Comment by A9G-Data-Droid** [comment]
I am currently using this library in a Blazor Server App targeting .NET 8.0 and it appears to work. That said, I looked at your PR and it looks fine. There are benefits to upgrading so I would like to see the PR approved.

**Comment by DanielCordell** [comment]
@A9G-Data-Droid I did manage to get it working without the upgrade too, but yeah would be good to see this upgraded.

**Comment by A9G-Data-Droid** [comment]
Cheers. Between this and #112 we would be up to date.

**Comment by serdarciplak** [comment]
Added this in #120 with other small fixes. It will be released in BlazorMonaco v3.2.0
