### ISSUE TITLE
Other supported languages

### ISSUE THREAD

**Issue by LUCKYONE-CC** [serdarciplak/BlazorMonaco#117]
Hi, I have been looking for a library or a Razor component that I can easily import into my project. However, it should support C#. Is this also possible here, or does anyone know of an alternative? I have already tested it and entering "csharp" under the language-property did not help. The Monaco Editor API does not explicitly say that it supports C#.

**Comment by serdarciplak** [comment]
As you can see [here](https://microsoft.github.io/monaco-editor/), Monaco Editor (and thus BlazorMonaco) supports `csharp`. You can use StandaloneEditorConstructionOptions.Language property in BlazorMonaco to set the language of an editor instance.
