### ISSUE TITLE
Diff Editor Merging

### ISSUE THREAD

**Issue by MMZAID01GitHub** [serdarciplak/BlazorMonaco#130]
On the main Monaco site https://microsoft.github.io/monaco-editor/ for the diff editor there is a bar in the middle that displays arrows for merging changes left or right. I couldn't find where this functionality exists in their docs, do you know if this is available for Blazor Monaco?

**Comment by serdarciplak** [comment]
BlazorMonaco `v3.2.0` uses MonacoEditor `v0.46.0`. That menu seems to be added in a newer MonacoEditor version. BlazorMonaco `v3.3.0` will use MonacoEditor `v0.52.2`. If you update, you'll get that menu too.
