### ISSUE TITLE
Deploying on Linux OS The Net Core platform uses this editor, but when accessed through a browser, the paste menu cannot be seen by right clicking

### ISSUE THREAD

**Issue by zangxq** [serdarciplak/BlazorMonaco#140]
. NET Core platform deployed under Linux OS integrates this editor, but when accessed through other computers(linux os or windows os, the right-click menu only shows the cut, copy menus , while the same program deployed on Windows can be seen cut, copy , and paste menus

**Comment by serdarciplak** [comment]
BlazorMonaco does not intervene with how MonacoEditor displays the context menu. Your issue may be related to 3 things;
- How OS-level clipboard permissions work on each OS and/or which permissions are provided to the browser instances.
- If you customize the context menu in your project, there may be something you're missing there.
- If it's not one of the above, it is possibly related to MonacoEditor itself. I would suggest creating an issue in the MonacoEditor repo [here](https://github.com/microsoft/monaco-editor).
