### ISSUE TITLE
Target `net9.0` for improved caching

### ISSUE THREAD

**Issue by meenzen** [serdarciplak/BlazorMonaco#142]
To make the new `MapStaticAssets` feature work properly, assemblies with embedded assets need to be targeting `net9.0`. By referencing the JS files like this, fingerprinting will ensure aggressive caching and cache busting:

```razor
<script src="@Assets["_content/BlazorMonaco/jsInterop.js"]"></script>
<script src="@Assets["_content/BlazorMonaco/lib/monaco-editor/min/vs/loader.js"]"></script>
<script src="@Assets["_content/BlazorMonaco/lib/monaco-editor/min/vs/editor/editor.main.js"]"></script>
```

Docs: https://learn.microsoft.com/en-us/aspnet/core/blazor/fundamentals/static-files?view=aspnetcore-9.0#deliver-assets-with-map-static-assets-routing-endpoint-conventions

**Comment by serdarciplak** [comment]
The fix is in the develop branch. It will be released in the next version.
