### ISSUE TITLE
OnChange event

### ISSUE THREAD

**Issue by svenboulanger** [serdarciplak/BlazorMonaco#17]
I believe the Monaco editor has an event for detecting a text change (`onDidChangeContent` on the model), but this hasn't been ported to BlazorMonaco (yet).

Is this going to be implemented (and if yes, when)?

**Comment by serdarciplak** [comment]
I've just added that event (and its siblings) and updated BlazorMonaco to v1.5.0. Just update it :)

**Comment by svenboulanger** [comment]
Thanks for the swift response.

I'm not sure if I'm doing something wrong, but the `OnDidChangeModelContent` does not fire (I'm simply trying to show a message in the console).

Is there something else that I should be doing to get this to work?

```
<MonacoEditor @ref="_scriptEditor" Id="script-editor" CssClass="full-height border" OnDidChangeModelContent="Update" ConstructionOptions="GetStyleOptions" />
```

**Comment by serdarciplak** [comment]
Actually, I've tested it and saw that working. As there are changes in js files (and browsers use caches) can you try reloading all resource files in the browser?

**Comment by svenboulanger** [comment]
Hi, thanks. I believe it must have been some kind of caching problem. I managed to get it working. Thanks!
