### ISSUE TITLE
Changing the suggestions box content

### ISSUE THREAD

**Issue by WAELKASSEM** [serdarciplak/BlazorMonaco#19]
Hello, I am looking to compile c# , by using Roslyn.
So I need to be able to change **the suggestions box content**. 
Can I do that with this package or not yet ?

**Comment by Apollo3zehn** [comment]
Hey, I had exactly the same issue and have searched through `Roslyn`, `VS code`, `OmniSharp-vscode` and `OmniSharp-Roslyn`. In the end I was able to utilize the `CompletionService` and the `SignatureHelpService` of `OmniSharp-Roslyn`. I have put together a small sample (with additional use of some Javascript):

![Monaco_Blazor_CSharp](https://user-images.githubusercontent.com/20972129/100616650-ad528f00-3319-11eb-94f1-de235e49da54.png)

https://github.com/Apollo3zehn/MonacoBlazorSample

Maybe this can be a starting point to add native support by `BlazorMonaco` with the need to use Javascript.

**Comment by WAELKASSEM** [comment]
@Apollo3zehn Thank you for your feedback and help. That's a very nice project.
I also found this package which is only a preview for .net conf 2020
[https://github.com/SteveSandersonMS/MonacoRazor/tree/master/MonacoRazor](url) 
can be downloaded as nuget too.

**Comment by Apollo3zehn** [comment]
Thanks for that link. I have just watched the .NET Conf video, it is very interesting. But it seems that currently this project offers a more advanced Blazor component. 

Unfortunately the sample project from SteveSanderson does not run on my computer. In the browser it fails to load `https://localhost:5001/_content/MonacoRazor/main.js`. For now I will continue integrating this project with Omnisharp but of course it would be great if Microsoft decides to provide an officially supported Monaco editor for blazor.

**Comment by WAELKASSEM** [comment]
Yes this project exposes more monaco features. Let's hope MSFT makes a Blazor component for Monaco.
If you'd like to run steve sanderson's monaco editor :

1. Create a new blazor project with **.net 5.0** using vs2019
2. Install the nuget package ,**make sure to tick the pre-release checkbox**
3. copy from **MonacoRazor.sample** the index page.

**Comment by Apollo3zehn** [comment]
Thank you, I will try that!

I have added support for hover so there is a way to get the type of infered variables:

![grafik](https://user-images.githubusercontent.com/20972129/100729353-f281ca00-33c8-11eb-8759-80d3ea210b6b.png)

**Comment by WAELKASSEM** [comment]
That's great. I'm just using roslyn for completion, it's a bit of head busting process :) .
**Looking forward to see your project as a nuget !**

**Comment by serdarciplak** [comment]
v3.1.0 of BlazorMonaco supports completion item providers. You can check that out.
