### ISSUE TITLE
Proposal: remove hardcoded style

### ISSUE THREAD

**Issue by dbulic** [serdarciplak/BlazorMonaco#2]
Hi there,
I propose that you remove the hardcoded ```style="min-height:100px;border:1px solid gray;``` in MonacoEditor.razor.
It's very easy to wrap the editor with a div containing that style, but impossible to remove the border when you hardcode it like it is.
I have no beef with min-height, but assume some people might want to have a one-liner Monaco here and there.

**Comment by Monedula1** [comment]
If you can't wait on the update I fixed this rather crudely like this (included this in a css file that is part of the project):
```
.editor {
    min-height: 800px !important;
    max-height: 800px !important;
    height: 800px !important;
    width: 100%;
}
```
Far from pretty but it does the job.

**Comment by serdarciplak** [comment]
Hi @dbulic I've changed it as you've suggested. Check out v1.2.2. Thanks.
