### ISSUE TITLE
Monaco Editor displays 

### ISSUE THREAD

**Issue by charlesjelliott** [serdarciplak/BlazorMonaco#23]
When displaying the BlazorMonaco editor in a Radzen Blazor application the control displays only about 2 pixels high making it unusable. All other controls appear normally. Can you suggest a remedy? I have checked the location of all the content links and scripts and everything appears to be correct. The Razor script is taken directly from your sample (which works fine). Screenshot attached below:
![MonacoBlazor](https://user-images.githubusercontent.com/29920751/101302776-80e9c600-3877-11eb-8d50-83038d801eb9.png)

**Comment by serdarciplak** [comment]
You can use css to set it's height. Everything is wrapped in a div with a class of monaco-editor-container. Just style it as you need.
