### ISSUE TITLE
All Events are triggered twice

### ISSUE THREAD

**Issue by albertoVieiraNeto** [serdarciplak/BlazorMonaco#27]
Hi, first off, awsome project.

When using the editor and registering **any** eventListener, for some reason the event is triggered twice, this can be reproduced on the demo app, just open the console and right click on the editor, you should see that "OnContextMenu" was "printed/triggered" twice.

Console Print:
![image](https://user-images.githubusercontent.com/25618042/106756760-5c5b6180-660e-11eb-950e-5fb0998d35c6.png)

**Comment by serdarciplak** [comment]
Hi @albertoVieiraNeto 
Thanks a lot for letting me know about the problem. I've solved it and updated to v1.6.1 Please check it out.
