### ISSUE TITLE
getValueInRange

### ISSUE THREAD

**Issue by GilShalit** [serdarciplak/BlazorMonaco#28]
Is there a problem with the implementation of ITextModel.getValueInRange() ?

When I include the following code in a OnMouseUp event
```
        Selection sel = await _editorSource.GetSelection();
        TextModel m = await _editorSource.GetModel();
        BlazorMonaco.Bridge.Range range = new BlazorMonaco.Bridge.Range(sel.StartLineNumber, sel.StartColumn, sel.EndLineNumber, sel.EndColumn);
        string s =  m.getValueInRange(range);
```
I get the following compilation error:
`'TextModel' does not contain a definition for 'getValueInRange' and no accessible extension method 'getValueInRange' accepting a first argument of type 'TextModel' could be found`

Or am I doing something wrong?

Or, is it possibly related to the open Pull request?

**Comment by serdarciplak** [comment]
TextModel methods are added to BlazorMonaco in version 2.0.0
