### ISSUE TITLE
How do you read the lines of code in the editor?

### ISSUE THREAD

**Issue by swmiller1** [serdarciplak/BlazorMonaco#29]
I am trying to read the lines of code in the editor, and the GetValue().ToString() does not work.  I have seen many people online having this issue with Monaco in general, and was wondering if you knew how to get to the lines of code in BlazorMonaco.  I really don't care how I get to them or what they come in as, but I need to see the lines of code.

**Comment by GilShalit** [comment]
Hi @swmiller1,

Are you able to compile with the TextModel.GetValue() call?

I get the following compilation error:
'TextModel' does not contain a definition for 'getValueInRange' and no accessible extension method 'getValueInRange' accepting a first argument of type 'TextModel' could be found`

Can you post the code of your call?

**Comment by swmiller1** [comment]
This is not full Monaco, it is BlazorMonaco that allows Monaco to be used in Blazor.  Not everything in Monaco works in BlazorMonaco, and I agree that TextModel.GetValue() was apparently one of the things that was not brought over (it does not work).  BlazorMonaco is open source, so you can play around with it and try to add that functionality, or we can wait for someone else to add it.

**Comment by WhitWaldo** [comment]
If you set the @ref value on the MonacoEditor itself, you can access the value with:

```
<MonacoEditor @ref="_editor" .../>

@code {
  private MonacoEditor _editor { get; set; }

  private async Task SomeEventCallback()
  {
    var code = await _editor.GetValue();
    //Do something with the string
  }
}
```
Note that the returned value includes \n for each of the linebreaks, so if you need the lines of code, it's a simple splitting exercise at that point to work out individual lines.

**Comment by serdarciplak** [comment]
TextModel methods are added to BlazorMonaco in version 2.0.0
