### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by Monedula1** [serdarciplak/BlazorMonaco#3]
Hi @serdarciplak I love your application but now I am trying to include it in a Razor Class Library and I get the error that is depends on Microsoft.AspNetCore.Components v 5.0.0.-preview 3
Is there a functionality in this dependency that is not covered in 3.1.6?

I have the privilege to use this in an innovative environment, but I can imagine that a lot of people don't want libraries that require their project to update to a non-release version. Now that WASM is officially released, could you change the dependencies to non-prerelease libraries?

Cheers,
Marijn

**Comment by serdarciplak** [comment]
Hi @Monedula1 You're right. It was just because of the state of the "include prerelease" checkbox in my Visual Studio settings :) I've changed it to be the latest stable version in v1.2.2. Thanks for letting me know.
