### ISSUE TITLE
Diff editor System.NullReferenceException

### ISSUE THREAD

**Issue by mkalinski93** [serdarciplak/BlazorMonaco#30]
Hey,

I´ve recreated your diffeditor implementation in my environment using the startup guide you´ve provided.
Unfortunately, when loading the page which contains the diff editor, it throws a System.NullReferenceException.

`Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NullReferenceException: Object reference not set to an instance of an object.
         at BlazorMonaco.MonacoDiffEditor.Dispose()
         at Microsoft.AspNetCore.Components.Rendering.ComponentState.Dispose()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.Dispose(Boolean disposing)
`

This is basically the implementation copied from your example which I tested.
`
<MonacoDiffEditor @ref="_diffEditor" Id="sample-diff-editor-123" ConstructionOptions="DiffEditorConstructionOptions" OnDidInit="EditorOnDidInit" OnKeyUpOriginal="EditorOnKeyUpOriginal" OnKeyUpModified="EditorOnKeyUpModified" />

@code {
    private MonacoDiffEditor _diffEditor { get; set; }
    private string ValueToSetOriginal { get; set; }
    private string ValueToSetModified { get; set; }

    private DiffEditorConstructionOptions DiffEditorConstructionOptions(MonacoDiffEditor editor)
    {
        return new DiffEditorConstructionOptions
        {
            OriginalEditable = true
        };
    }

    private async Task EditorOnDidInit(MonacoEditorBase editor)
    {
        // Get or create the original model
        TextModel original_model = await MonacoEditorBase.GetModel("sample-diff-editor-originalModel");
        if (original_model == null)
        {
            var original_value = "\"use strict\";\n" +
                            "function Person(age) {\n" +
                            "	if (age) {\n" +
                            "		this.age = age;\n" +
                            "	}\n" +
                            "}\n" +
                            "Person.prototype.getAge = function () {\n" +
                            "	return this.age;\n" +
                            "};\n";
            original_model = await MonacoEditorBase.CreateModel(original_value, "javascript", "sample-diff-editor-originalModel");
        }

        // Get or create the modified model
        TextModel modified_model = await MonacoEditorBase.GetModel("sample-diff-editor-modifiedModel");
        if (modified_model == null)
        {
            var modified_value = "\"don't use strict\";\n" +
                            "furction Person(age_is_just_a_number) {\n" +
                            "	if (age_is_just_a_number) {\n" +
                            "		this.age_is_just_a_number = age_is_just_a_number;\n" +
                            "	}\n" +
                            "}\n" +
                            "Person.prototype.getAge = function () {\n" +
                            "	return this.age_is_just_a_number;\n" +
                            "};\n" +
                            "//Really, it is just a number people!";
            modified_model = await MonacoEditorBase.CreateModel(modified_value, "javascript", "sample-diff-editor-modifiedModel");
        }

        // Set the editor model
        await _diffEditor.SetModel(new DiffEditorModel
        {
            Original = original_model,
            Modified = modified_model
        });
    }

    private void EditorOnKeyUpOriginal(KeyboardEvent keyboardEvent)
    {
        Console.WriteLine("OnKeyUpOriginal : " + keyboardEvent.Code);
    }

    private void EditorOnKeyUpModified(KeyboardEvent keyboardEvent)
    {
        Console.WriteLine("OnKeyUpModified : " + keyboardEvent.Code);
    }

    private async Task SetValueOriginal()
    {
        Console.WriteLine($"setting original value to: {ValueToSetOriginal}");
        await _diffEditor.OriginalEditor.SetValue(ValueToSetOriginal);
    }

    private async Task SetValueModified()
    {
        Console.WriteLine($"setting modified value to: {ValueToSetModified}");
        await _diffEditor.ModifiedEditor.SetValue(ValueToSetModified);
    }

    private async Task GetValueOriginal()
    {
        var val = await _diffEditor.OriginalEditor.GetValue();
        Console.WriteLine($"original value is: {val}");
    }

    private async Task GetValueModified()
    {
        var val = await _diffEditor.ModifiedEditor.GetValue();
        Console.WriteLine($"modified value is: {val}");
    }

    private async Task AddCommand()
    {
        await _diffEditor.ModifiedEditor.AddCommand((int)KeyMode.CtrlCmd | (int)KeyCode.Enter, (editor, keyCode) =>
        {
            Console.WriteLine($"Ctrl+Enter : Original Editor command is triggered. ({editor.Id})");
        });
    }

    private async Task AddAction()
    {
        await _diffEditor.ModifiedEditor.AddAction("testAction", "Test Action", new int[] { (int)KeyMode.CtrlCmd | (int)KeyCode.KEY_D, (int)KeyMode.CtrlCmd | (int)KeyCode.KEY_B }, null, null, "navigation", 1.5, (editor, keyCodes) =>
        {
            Console.WriteLine($"Ctrl+D : Modified Editor action is triggered. ({editor.Id})");
        });
    }
}`

I´m targeting .Net 5.0 and use Blazor.ServerSide

**Comment by serdarciplak** [comment]
Hi @mkalinski93 
For a reason, a seemingly not necessary MonacoEditor.Dispose call is being made before it is even rendered in a server-side project. That was causing the crash and a simple null check solved the issue. I'll push the changes with the new release (v2.0.0) today or tomorrow.
