### ISSUE TITLE
Theming for DiffEditor

### ISSUE THREAD

**Issue by mkalinski93** [serdarciplak/BlazorMonaco#31]
Hey,

I was just curious to find out if there´s a "SetTheme" method for the diff editor.
The DiffEditorConstructionOptions doesn´t have a "Theme" property as well.

**Comment by serdarciplak** [comment]
Actually, there is a property named "Theme" in the DiffEditorConstructionOptions class. But looks like I've missed adding it to the C# class. I'll add it in the next release. Till then, you can use the static SetTheme method in the MonacoEditorBase class.

**Comment by serdarciplak** [comment]
I've added the missing property to the DiffEditorConstructionOptions class. It's available in version 2.1.0
