### ISSUE TITLE
FeatureRequest: compilerOptions 

### ISSUE THREAD

**Issue by mkwired** [serdarciplak/BlazorMonaco#32]
Could you please add the ability to change the `compilerOptions` values for the TypeScript language or explain how someone else could do it?

https://stackoverflow.com/questions/40545329/property-includes-does-not-exist-on-type-string

**Comment by serdarciplak** [comment]
The conversation at that stackoverflow link does not look like it's about Monaco Editor or Blazor at all. Trying to understand, I can imagine that you may want to write TypeScript in Monaco Editor and want the auto-completion to obey different rules than the ones it does. Is this what you mean?

**Comment by mkwired** [comment]
I want to be able to modify the compilerOptions object.  The BlazorMonaco control is showing me a syntax error where the `includes` method in called.

 `(foo as string[]).includes("bar")`

**Comment by serdarciplak** [comment]
This is not an issue about BlazorMonaco. It's about the pre-configured TypeScript language rules in Monaco Editor. Monaco Editor supports you to register your custom language and rules. BlazorMonaco does not have support for registering languages yet. But you can register your custom language on JavaScript and use it via its name in BlazorMonaco.

You can keep track of BlazorMonaco's support for registering custom languages in the issue at #26
