### ISSUE TITLE
More API type bindings

### ISSUE THREAD

**Issue by hez2010** [serdarciplak/BlazorMonaco#33]
# More API type bindings

Hello, thanks for this awesome project. 

Monaco has plenty of APIs and types, it'll be a non-trivial work if writing those C# type bindings by hand. 

To make development of monaco-related C# projects eaiser, I've generated monaco 0.22.3 C# type bindings using [TypedocConverter](https://github.com/hez2010/TypedocConverter) and saved it to https://gist.github.com/hez2010/3d3e493f8e434f1dc758438c4a2c9dab. 

If you need to write C# type bindings for monaco, I think you can make use of the auto-generated type bindings so that you don't need to write most of them manually.

**Comment by serdarciplak** [comment]
Looks cool. I'll check it out when I need that. Thanks for mentioning.
