### ISSUE TITLE
Blazor server side

### ISSUE THREAD

**Issue by adiaz-iot** [serdarciplak/BlazorMonaco#34]
Been trying to use it on a Blazor Server app and it seems to load fine but the component has no height, it shows as a very thin line. Is this something I'm missing or an incompatibility with Blazor Server?.
![blazormonaco_issue](https://user-images.githubusercontent.com/79848001/109957804-bd498880-7ce5-11eb-81de-cb59ca353c38.png)

**Comment by serdarciplak** [comment]
Duplicate of #24
