### ISSUE TITLE
LineNumber property

### ISSUE THREAD

**Issue by albertoVieiraNeto** [serdarciplak/BlazorMonaco#35]
Hi, i'm trying to "bind" two editors together, this just means that the last "line number" of the first editor will become the first linenumber of the second editor, just to allow me to have a "read only" area on the "editor"

![image](https://user-images.githubusercontent.com/25618042/109979464-af900500-7cdd-11eb-86e0-06eb19aa675f.png)
should this work? knowing that most of this will run as "interop"

![image](https://user-images.githubusercontent.com/25618042/109979652-e1a16700-7cdd-11eb-8a85-6a1d440c6dbe.png)
a code very "similiar" will run on the "playground" without issues.

looking at the "create" function used in the [JsInterop](https://github.com/serdarciplak/BlazorMonaco/blob/4f0fb9f062fa2d913677bd3043aaa4e1a97285d6/BlazorMonaco/wwwroot/jsInterop.js#L25) File, maybe that the function is being set as a "string".

am i doing something wrong?

**Comment by serdarciplak** [comment]
Currently, C# LineNumbers property is just a string, but it can be a function as well in JavaScript. I'll figure out a way to achieve the same thing in C# and publish a new version of BlazorMonaco this weekend.

**Comment by victorperez2911** [comment]
Hi @serdarciplak 

Any news on this subject?

**Comment by serdarciplak** [comment]
Sorry. I couldn't find time for this yet. But I see this as a priority item for this repo. I'll solve it asap.

**Comment by serdarciplak** [comment]
I've added support for this in v2.1.0. Just set the LineNumbersLambda property of the construction options to a lambda and it will be called by the editor when needed.

**Comment by albertoVieiraNeto** [comment]
Hi and thanks for the attention.

I was testing, and when using the the new property LineNumbersLambda when the page loads the components, it throws the following:

![image](https://user-images.githubusercontent.com/25618042/114918694-c0b05380-9dfd-11eb-873e-a7d8f0583937.png)

![image](https://user-images.githubusercontent.com/25618042/114919111-3b796e80-9dfe-11eb-940b-cf670ce9a24d.png)

My project runs on blazor-side, this functionality should be supported in this model?

**Comment by serdarciplak** [comment]
I haven't tested it on a server-side app. I'll check it out.

**Comment by victorperez2911** [comment]
Hi @serdarciplak 

Did you manage to take the test?

**Comment by psantosl** [comment]
Any news about this? I'm still seeing it running in server-side mode

**Comment by serdarciplak** [comment]
I finally had time to have a look at this and I think I have a fix. Here is an explanation of the new flow;

- A new JS-side cache is added for the line numbers.
- When MonacoEditor requests a line number for the first time, a dotnet call is initiated and an empty string is returned as the line number.
- When an async dotnet call completes, it adds the returned value to the JS-side cache.
- When all active dotnet calls complete, the line numbers are redrawn. In this redraw, the lineNumbers JS function returns the cached values and Monaco Editor displays these values as the line numbers.
- Also, a new editor instance method named ReloadLineNumbers is added. It can be used if the dotnet side needs to reset the JS-side cache and provide new line numbers.

@psantosl It would be great if you can review the PR #147 as you already know the context here.

**Comment by psantosl** [comment]
Sorry! I haven't checked my notifications in a while!! :-(
