### ISSUE TITLE
ITextModel.GetAllDecorations() should return an array

### ISSUE THREAD

**Issue by GilShalit** [serdarciplak/BlazorMonaco#37]
Hi, adding the ITextModel bindings is a huge help.

I thing there is a small error in the `GetAllDecorations()`.  you have it returning a single `ModelDecoration` object, but the documentation says the returned object should be an array - `ModelDecorations[]`, which is also implied by the function name.

Thanks again!

**Comment by serdarciplak** [comment]
You're right. My bad. I'll correct that this weekend.

**Comment by serdarciplak** [comment]
I've corrected this in v2.1.0
