### ISSUE TITLE
how to format the code

### ISSUE THREAD

**Issue by khaledafify** [serdarciplak/BlazorMonaco#38]
how can i trigger the action

` 'editor.action.formatDocument'

to format the code ?

**Comment by serdarciplak** [comment]
There's nothing like `editor.action.formatDocument` in Monaco Editor. Can you please explain what you mean?

**Comment by khaledafify** [comment]
i have initialized MonacoEditor Component in my page and i need to format the code

ref : https://github.com/microsoft/monaco-editor/issues/32

**Comment by khaledafify** [comment]
@serdarciplak is this action applicable to perform ?

**Comment by serdarciplak** [comment]
Hi @khaledafify 
It's suggested to use the editor.trigger() method in the link you've sent. BlazorMonaco already supports that method. So, you may use it to invoke the editor.action.formatDocument action.

**Comment by khaledafify** [comment]
thank you @serdarciplak 
I'll try it tomorrow.
