### ISSUE TITLE
DeltaDecoration

### ISSUE THREAD

**Issue by Monedula1** [serdarciplak/BlazorMonaco#4]
Hi,
I have extended the projects with 2 methods that will Set and Reset DeltaDecorations. I would like to make a pull request. Could you open the project so I can send a pull requests to the project?

**Comment by serdarciplak** [comment]
Hi @Monedula1 I've added you as a collaborator. You can now create a branch, push your changes there and create a pull request for merging to the master branch.

**Comment by Monedula1** [comment]
Ok. somehow the change is weird. I only had a small change but apparently github sees a lot of differences.

See at the bottom of that file the region decorations., That should be the only chance. Perhaps you just ignore my check-in and add the 2 sections at the bottom yourself???

Btw is there a way that I can get directly into contact with you? 
My twittter handle is @monedula_

**Comment by Monedula1** [comment]
Thought of an extension. I will delete this branch and make a new one and check it in when done. That's easier.

**Comment by serdarciplak** [comment]
Hi @Monedula1 I was really busy at work, so I couldn't find time to check GitHub. Sorry.

Different line ending styles cause git to think differences are more than they actually are. Possibly this was the case with your first commit.

I'll check your commit and merge it to master shortly.

I've followed you on Twitter. I'm @serdarciplak

**Comment by serdarciplak** [comment]
@Monedula1 I've reorganized the code and made the changes below. Can you please check it if all is fine for you?

- Moved delta decoration id list from Javascript to C# and associated them with editor instances. Someone may want to use multiple editor instances concurrently and decorations of each instance should be seperated.
- Renamed some objects and methods to stay in parallel to the javascript api.
- Reorganized the code.
- Added delta decorations to the sample app.

**Comment by Monedula1** [comment]
Hi @serdarciplak No worries, I too get busy at work :) And indeed my settings are such that js files tabs are 2 spaces. I redid that in my 2nd checkin.
Clearly you have a low more experience converting js libraries to c#. I was able to refactor my code with yours to make it work. One small thing that could be added perhaps; when I do not initialize the DeltaDecorationIds with `= new string[] { }` I get an error. Perhaps make the default value an empty string if null is provided. Just minor. But I like the new stuff a lot!
