### ISSUE TITLE
Error when ConstructionOptions isn't set

### ISSUE THREAD

**Issue by hjrb** [serdarciplak/BlazorMonaco#43]
Hello, 

when the function reference property "ConstructionOptions" isn't set, one get's an error:
Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at BlazorMonaco.MonacoEditor.OnAfterRenderAsync(Boolean firstRender)

Maybe this works as designed but a component should not cause a page exception when properties aren't said - right?

**Comment by serdarciplak** [comment]
Fixed. It will be released `v3.0.1`

**Comment by isatahiri** [comment]
Any ETA for the 3.0.1 ?

**Comment by sfmskywalker** [comment]
@hjrb Thanks for reporting this issue, it helped me figure out the workaround. Admittedly, most users will probably always set this property. For newcomers like myself, however, it's best to not cause a page exception when not setting the `ConstructionOptions`, but instead, initialise it internally.
