### ISSUE TITLE
Json & registerCompletionItemProvider

### ISSUE THREAD

**Issue by vinit21** [serdarciplak/BlazorMonaco#48]
Hello , 

Thanks for maintaining this repo . For guys like me who are not strong with Javascript such help is always appreciated. .

 I am able to change language to Json but I don’t know how to implement  registerCompletionItemProvider In blazor project. I want to provide customise suggestions.

**Comment by serdarciplak** [comment]
RegisterCompletionItemProvider support is added in v3.1.0
