### ISSUE TITLE
Unable to bind value to c# object. 

### ISSUE THREAD

**Issue by CliffBDev** [serdarciplak/BlazorMonaco#55]
Is there a way to data-bind the value to a string or a string property of an object? I have not seen any documentation on data binding at all.

**Comment by codymullins** [comment]
@QuietDesperationDev I didn't see it either. I accomplished it somewhat manually in [Spacetime](https://github.com/getspacetime/spacetime/blob/main/src/Spacetime/Shared/Components/Inputs/Code.razor). Fairly untested but it seems to work from first glance.

**Comment by serdarciplak** [comment]
BlazorMonaco does not support two-way value binding as that would require the whole editor value to be passed between JS and Blazor on every value change. And it's even worse for Blazor server apps, as the data also needs to be transferred between the client and the server. As the value gets bigger, things would get even slower and completely break at some point.

As suggested in the above comment, you can manually call editor.GetValue() to get the value only when you need it.
