### ISSUE TITLE
Adding languages

### ISSUE THREAD

**Issue by mihai-cloudbrick** [serdarciplak/BlazorMonaco#58]
Hi, 
Im not an expert, but i want to add different languages. Right now im trying to add kusto and looks that its not working. Do you have any small tutorial on how to do it. I know its nut an issue, but will be much appreciated.

**Comment by serdarciplak** [comment]
Hi. BlazorMonaco does not currently support doing this in C#. But you can configure the language in javascript and use it via its name in C#. Have a look at the link below for configuring the language in js.
https://ohdarling88.medium.com/4-steps-to-add-custom-language-support-to-monaco-editor-5075eafa156d
