### ISSUE TITLE
Add CssStyle - Parameter

### ISSUE THREAD

**Issue by beckma** [serdarciplak/BlazorMonaco#6]
Is it possible, to add the CssStyle-Parameter?

![image](https://user-images.githubusercontent.com/6991499/83242424-b01ecc80-a19c-11ea-96f6-f80e08f331a5.png)

![image](https://user-images.githubusercontent.com/6991499/83242487-ccbb0480-a19c-11ea-8ad5-fa004289fac9.png)

![image](https://user-images.githubusercontent.com/6991499/83242579-ee1bf080-a19c-11ea-9269-aefc6004a5bd.png)

![image](https://user-images.githubusercontent.com/6991499/83242745-2c191480-a19d-11ea-9bcd-68961ef19d18.png)

**Comment by serdarciplak** [comment]
Hi @beckma 
Why don't you use CssClass instead? It's possible to achieve the same effect in your screenshots using css classes. Just move the style attributes (height and width) to a css file and set the CssClass property of the MonacoEditor instance accordingly. If the screenshots are not clear on why you need CssStyle, please let me know your use case.

**Comment by serdarciplak** [comment]
Hi @beckma Please let me know if there's a use case where CssClass is not working and I'll reopen the issue and add this feature. Thanks.
