### ISSUE TITLE
Scrolling should support limit detection

### ISSUE THREAD

**Issue by gregsdennis** [serdarciplak/BlazorMonaco#62]
Currently the scrolling settings allow me to always capture the scroll events or not.

When always capturing, the page doesn't scroll at all when scrolling with the mouse over the component, even if the component content can't scroll farther.  (This is the setting I currently have on https://json-everything.net)

When not always capturing, the scrolling seems inconsistent.  Sometimes the event is captured by the component, but other times it's captured by the page.  And it even happens with the multiple events that occur during a single scroll action.  What results is a jerky motion of both the component content and page.

What I'd like is a setting where the component always captures scroll events until the content can no longer be scrolled, then the events are forwarded to the page.

**Comment by serdarciplak** [comment]
Hi. Scrolling and event management is done by the Monaco Editor JS library. You can create an issue there : https://github.com/Microsoft/monaco-editor
