### ISSUE TITLE
BlazorMonaco support

### ISSUE THREAD

**Issue by David-Moreira** [serdarciplak/BlazorMonaco#67]
@serdarciplak 
It seems like you might've stopped supporting the project, it is a pretty good initiative and project, but it is a shame it is not being improved && maintained, even people's contributions (pull requests) do not seem to be considered.

It is understandable that it's a side project and you may have other priorities but I'm sure there are people pretty interested in the project being maintained.

Would you mind that someone pick this up and maintains it? And would anyone be willing to? :)

**Comment by serdarciplak** [comment]
@David-Moreira
Thanks for the heads up and your interest. You're right that I was distracted with some other priorities but now I'm back and it's good to see that people care about this project 🙂 I'll start maintaining the project again. Of course, that does not mean that I'll be able to provide immediate support for everything, but I'll do my best.
