### ISSUE TITLE
Could not create monacoeditor

### ISSUE THREAD

**Issue by furesoft** [serdarciplak/BlazorMonaco#69]
Hi,
I was trying to add blazormonaco to my webassembly blazor project, but I get an exception that is not defined

`Could not find 'blazorMonaco.editor.create'`

**Comment by serdarciplak** [comment]
Looks like the js files are missing. Just make sure that you've followed the instructions in the [Getting Started](https://github.com/serdarciplak/BlazorMonaco#get-started) section of the README file.
