### ISSUE TITLE
Change ConstructionOptions

### ISSUE THREAD

**Issue by pcsolutioncz** [serdarciplak/BlazorMonaco#77]
Hi, 
is it possible to change **ConstructionOptions** in Blazor after event?
I need to change the language in the editor.

Example:

```
<StandaloneCodeEditor @ref="FragmentCode" Id="Code" ConstructionOptions="EditorOptions" />
@code
{
    private void ChangeLanguage (string lang)
    {
       // Change EditorOptions here.
    }
    private StandaloneEditorConstructionOptions EditorOptions(StandaloneCodeEditor editor)
    {
        return new StandaloneEditorConstructionOptions
        {
            AutomaticLayout = true,
            Language = "html"
        };
    }
}
```

Thank you
David

**Comment by pcsolutioncz** [comment]
Hi, thank you for the hint, but I can't see a method for changing language in **EditorUpdateOptions**.
Can you send me an example?
Thank you
David

**Comment by serdarciplak** [comment]
Hi.
You can use the `BlazorMonaco.Global.SetModelLanguage()` method with the model instance of your editor.

```csharp
Global.SetModelLanguage(editor.GetModel(), "javascript");
```

BTW, as BlazorMonaco is just a wrapper for the Monaco Editor JS library, you can use its [documentation](https://microsoft.github.io/monaco-editor/) for reference.
