### ISSUE TITLE
Hi, thank you for the hint, but I can't see a method for changing language in **EditorUpdateOptions**.

### ISSUE THREAD

**Issue by wmchuang** [serdarciplak/BlazorMonaco#78]
Hi, thank you for the hint, but I can't see a method for changing language in **EditorUpdateOptions**.
Can you send me an example?
Thank you
David

_Originally posted by @pcsolutioncz in https://github.com/serdarciplak/BlazorMonaco/issues/77#issuecomment-1432555305_

**Comment by serdarciplak** [comment]
Hi.
You can use the `BlazorMonaco.Global.SetModelLanguage()` method with the model instance of your editor.

```csharp
Global.SetModelLanguage(editor.GetModel(), "javascript");
```

BTW, as BlazorMonaco is just a wrapper for the Monaco Editor JS library, you can use its [documentation](https://microsoft.github.io/monaco-editor/) for reference.

**Comment by serdarciplak** [comment]
@gregsdennis I agree with you but that's how Microsoft has decided to implement it. BlazorMonaco just follows the original Monaco Editor's interface.
