### ISSUE TITLE
BlazorMonacoGlobals

### ISSUE THREAD

**Issue by bitrott** [serdarciplak/BlazorMonaco#83]
From your migration guide "Static methods in the MonacoEditor and MonacoEditorBase classes (e.g. SetTheme, Colorize, etc) are removed from the editor class and grouped together under a new class named BlazorMonacoGlobals."

I pulled code... no class by that name exists. There is a "Globals". 

Also, there's a lot of changes to this API! Any plan to document any of this?

**Comment by sbruyere** [comment]
Somebody made a PR (https://github.com/serdarciplak/BlazorMonaco/pull/76) to update the documentation, but not merged yet. 
The workaround is to use BlazorMonaco.Editor.Global.
@serdarciplak Is the project still maintened ?

**Comment by serdarciplak** [comment]
I've fixed the README file but it's currently in the develop branch waiting to be published in v3.1.0 soon.
