### ISSUE TITLE
Add code suggestions for intellisense

### ISSUE THREAD

**Issue by vcarlucci** [serdarciplak/BlazorMonaco#85]
**Description**

Hi @serdarciplak , I am looking for a simple way to add coding suggestions for the editor intellisense. 
I need this to add for each editor I'm using some specific suggestions, best would be somehow to add this in the editor constructor.

Nice to have, each suggestion would have a description, which usually is also shown in the intellisense.

**Editor**
Custom suggestions example (strings):

Logservice.Start()
Logservice.GetState()
Logservice.ErrorCode

**Editor** 2
Custom suggestions example

Backend.WaveFilter.Pause()
Backend.WaveFilter.Run()
Backend.Services.Execute()
Simulation.Enable

// ---------------------------------------------------

**Actual Solution Concept with Blazor**

I am using Blazor where I initialize each editor by a list "CodeList" and have now to add to each editor specific suggestions like already described.

**Html**

```
@foreach (var item in CodeList)
{
    @*Local function (constructor)*@
    StandaloneEditorConstructionOptions EditorConstruction(StandaloneCodeEditor editor)
    {
        @*setup editor options*@
        return new StandaloneEditorConstructionOptions
                    { 
                        Language = "csharp",
                        GlyphMargin = true,
                        Value = item.Value,
    };
        @*EditorCollection.Add(editor); // used for later data collection when inside editor changes*@
    }
    @*Editor control*@
    <StandaloneCodeEditor ConstructionOptions="EditorConstruction"  />
    <br />
}
```

**Code behind**

```
@code {
    public Dictionary<string, string> CodeList { get; set; } = new Dictionary<string, string>();

    protected override async Task OnInitializedAsync()
    {
        // add some sample snippets
        CodeList.Add("SnippetKey1", "snippet1 code..");
        CodeList.Add("SnippetKey2", "snippet2 code..");
    }

}
```

**The Suggestion**

The suggestions collected in the "CodeSuggestions" list would be needed to add to the editor, which are then shown and selectable by the intellisense.

```
public class Suggestion
    {
        public string Item { get; set; } = string.Empty;
        public string Description { get; set; } = string.Empty;
        public string Typ { get; set; } = string.Empty;
    }

    List<Suggestion> CodeSuggestions = new List<Suggestion>();

    public void InitSuggestions()
    {
        CodeSuggestions.Add(new Suggestion() { Item = "Logservice.Start()", Description= "Starts the backend log service.", Typ="Method" });
        CodeSuggestions.Add(new Suggestion() { Item = "Logservice.ErrorCode", Description = "Get the log service error code", Typ = "String" });
    }
```

Any simple solution available to link these suggestions to a editor?

Maybe this intellisense suggestion solution would be a feature extension for your sample project page "Code Editor", I think this could be used in most scenarios..

**Comment by serdarciplak** [comment]
This is just a wrapper around the Monaco Editor js library. You can provide feature suggestions in its repo [here](https://github.com/microsoft/monaco-editor).

If you can have a look at the `RegisterCompletionItemProvider` method and its parameters, you can find some things that may help you.
