### ISSUE TITLE
MAUI Blazor Hybrid support

### ISSUE THREAD

**Issue by DapperMickie** [serdarciplak/BlazorMonaco#86]
Is it possible to get this working on .net maui blazor hybrid?
I tried it and desktop seems to be just fine, though mobile support isn't that good.
Is this a Monaco issue or do you think it could be fixed with css? (Because I think most of the issues are actually positioning and styling related)

**Comment by serdarciplak** [comment]
Unfortunately, Microsoft does not support mobile browsers for Monaco Editor. See [here](https://github.com/microsoft/monaco-editor#:~:text=Is%20the%20editor%20supported%20in%20mobile%20browsers%20or%20mobile%20web%20app%20frameworks%3F).
