### ISSUE TITLE
When pressing '{' on keydown code it is saying sqaure bracket code how to get curly bracket pressed on not?

### ISSUE THREAD

**Issue by snehabihani** [serdarciplak/BlazorMonaco#89]

**Comment by serdarciplak** [comment]
Key codes correspond to keyboard keys, not characters. As you can see [here](https://microsoft.github.io/monaco-editor/typedoc/enums/KeyCode.html#BracketLeft), the `BracketLeft` key code is used for the '[{' key on a US keyboard.

If you need to listen to characters, you can use the `OnDidChangeModelContent` event of the editor instance.
