### ISSUE TITLE
Editor is only created the first time the component is initialized

### ISSUE THREAD

**Issue by HillPhelmuth** [serdarciplak/BlazorMonaco#9]
It seems that the bridge will only create the Monaco Editor one time. Once the component is disposed, it appears that the Monaco Editor will no longer be created. After that, only the container html element is created. 
Is there currently a way to generate the Editor more than once? Perhaps I missed something, but I suspect this would require a change to the interop.

**Comment by serdarciplak** [comment]
The problem is solved in v1.3.1. Please check it out.
