### ISSUE TITLE
How do I set the start line for my code editor using Blazor Monaco?

### ISSUE THREAD

**Issue by BelloMary1** [serdarciplak/BlazorMonaco#91]
By default the start line of the code within the editor is 1, let's say I want to set it to start from a different value, such as 37. How do I configure the start line?

**Comment by serdarciplak** [comment]
The JS editor does not support doing this with a construction option. But I think you can subscribe to the `OnDidInit` event of the editor instance, and use the `SetPosition` method there to set the cursor position on init.
